### DISCUSSION TITLE
Trouble with document_exporter

### DISCUSSION THREAD

**Discussion by mepi0011** [jonaswinkler/paperless-ng#1317] [Support] [answered]
Hello,

when I try to backup paperless on my external USB device, I get just the error, that the path does not exist.

`docker-compose exec webserver document_exporter  /media/backup/Backup/paperless-ng`
`CommandError: That path doesn't exist`

The path exist, and I can change to this folder with `cd /media/backup/Backup/paperless-ng`.

Could this a permission issue?

My docker/paperless setup:

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: <secret>
      POSTGRES_PASSWORD: <secret>

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8001:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /srv/dev-disk-by-label-data/paperless/paperless-export:/usr/src/paperless/export
      - /srv/dev-disk-by-label-data/paperless/paperless-inbox:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

volumes:
  data:
```
