### DISCUSSION TITLE
Cannot host paperless-ng permission issues [Docker]

### DISCUSSION THREAD

**Discussion by IAmBaut** [jonaswinkler/paperless-ng#1335] [Support]
Hello,
I have recently switched to paperless-ng on Docker and previously used the linuxserver.io image (linuxserver/paperless-ng)[https://github.com/linuxserver/docker-paperless-ng]. That image worked fine, but by default only has english as language for ocr enabled and I did not manage to install other languages (the same environmental variables as the main image did not work), so I wanted to migrate to the main image. 
As such I have created the following docker-compose (using Portainer)
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperlessusername
      POSTGRES_PASSWORD: mypasswordishere

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /path/paperless-ng/data:/usr/src/paperless/data
      - /path/paperless-ng/media:/usr/src/paperless/media
      - /path/paperless-ng/export:/usr/src/paperless/export
      - /path/paperless-ng/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
volumes:
  pgdata:
```
I have removed comments and replaced paths/password obviously, but apart from that this is the whole config.
If I deploy this stack the broker and db show that they are "ready to accept connections", the webserver container stays in a "starting" state. Looking into the logs shows me:
`PermissionError: [Errno 13] Permission denied: '/usr/src/paperless/src/../data/log'`
which tells me there is a permission issue [as mentioned in the docs](https://paperless-ng.readthedocs.io/en/latest/troubleshooting.html#permission-denied-errors-in-the-consumption-directory).
A quick `sudo stat /path/paperless-ng | grep "Uid.*" -o`
returns `Uid: (    0/    root)   Gid: (    0/    root)`. So the folder is owned by root instead of me (1000:1000). 

I am truthfully not sure why that is the case despite me entering the correct USERMAP_UID and USERMAP_GIP environmental variables. I'm not very familiar with permission management in general, but if I go into the docker container and inspect `/etc/subuid` it is `paperless:100000:65536` which to my knowledge should be 1000 as uid instead right?

If I add permissions to the folder and subfolders manually with `sudo chown -R 1000:1000 /path/paperless-ng` I can change the ownership from root to 1000:1000.

But if I now restart the webserver container the "permission denied" error is gone, but instead I get `
django.db.utils.OperationalError: FATAL:  password authentication failed for user "paperless"`.

I am out of ideas how I should fix this, as creating the folders anew seems to make them owned by 0:0 instead of me, despite the USERMAP variable and changing ownership after the fact results in password authentification errors.

I have looked in the issues here and it was often suggested that there could be ownership issues on network drives, but in my case the relevant directories are local (I do host samba, so they technically are network connected, but the original directory is local. Samba also doesn't cause similar issues with any other docker container I know of).

Really would appreciate any help on how to fix this issue and get paperless-ng to run.
