### DISCUSSION TITLE
Failed Deploy; docker-comose.yml

### DISCUSSION THREAD

**Discussion by cjax82** [jonaswinkler/paperless-ng#1353] [Support] [answered]
Trying to deploy via Portainer and keep receiving the following error:
![image](https://user-images.githubusercontent.com/43307502/135263947-8ad656d7-b804-490f-976f-484eaeb4f96b.png)
[portainer-paperless deployment.txt](https://github.com/jonaswinkler/paperless-ng/files/7251674/portainer-paperless.deployment.txt)

Stack code (attached), added the following changes to meet as directed from the compose file as it would not deploy at all initially.

1. USERMAP_UID: 1026
2. Enable - PAPERLESS_TIME_ZONE: Europe/London
3. Enable - PAPERLESS_OCR_LANGUAGE: eng
4. Assigned volumes -
      **data**: /volume1/docker/paperless/data:/data
      **media**: /volume1/ck-data/paperless
      **pgdata**: /volume1/docker/paperless:/pgdata

**Comment by TheFehr** [comment]
I'm not sure if this
 ```
volumes:
    data: /volume1/docker/paperless/data:/data
    media: /volume1/ck-data/paperless
    pgdata: /volume1/docker/paperless:/pgdata
```
works.

Just replace the left part of the volume mappings up top by the servies with the left part you set down here.

```
volumes:
    - /volume1/docker/paperless/data:/usr/src/paperless/data
```
And so on

**Reply by cjax82** [reply]
I went back and made the adjustments, with a new issue...
![image](https://user-images.githubusercontent.com/43307502/135350453-acc9aba4-f604-407f-b84e-0c50be575018.png)

The server I am trying to deploy this on is a Synology, running latest DSM 7 ver with all updates (one was just released this week).  Just trying to provide as much info to aide at this point.  That I recall, I have gone into the "docker-compose.portainer.yml" originally when it would not deploy and pulled the compose code from there to post through portainer and deploy as a new stack through editor.

**Comment by TobenderZephyr** [comment, marked as answer]
Your line must start with a string, which is done with `-`.

You can reference directly to a (1) source directory or use (2) docker volumes, where actual data is then stored under /usr/lib/docker/volumes.

(1):
The compose file would look like this (beware of sufficient whitespaces!)
```
version: "3.9"

services:
  db:
    image: db
    volumes:
      - /path/to/folder:/var/lib/db
```

(2):
This one is referencing the path again at the end of the compose file.

```
version: "3.9"

services:
  db:
    image: db
    volumes:
      - data-volume:/var/lib/db

volumes:
  data-volume:
```
