### DISCUSSION TITLE
Issues with accessing paperless-ng through SWAG

### DISCUSSION THREAD

**Discussion by SyRaza** [jonaswinkler/paperless-ng#1370] [Support] [answered]
I'm using the docker-compose version of paperless-ng and have it up and running and can access it locally through my LAN. However, when trying to access it through SWAG, I get a 502 error bad gateway. 

I'm fairly certain it's my swag configuration for paperless-ng but I don't know what I'm doing wrong. 

Here is my conf from SWAG. 

```
## Version 2021/05/18
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name paperless.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app paperless;
        set $upstream_port 8010;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

    location ~ (/paperless)?/api {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app paperless;
        set $upstream_port 8010;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    
    
    }
}
```

Here is my docker compose for paperless-ng. I didn't include redis in this because I already have redis up and running for something else.
```

###############################################################
#                       Paperless-NG                          #
###############################################################

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    networks:
      - lsio
    volumes:
      - $USERDIR/docker/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: (redacted)
      POSTGRES_USER: (redacted)
      POSTGRES_PASSWORD: (redacted)

  paperless:
    image: jonaswinkler/paperless-ng:latest
    container_name: paperless
    restart: unless-stopped
    networks:
      - lsio
    depends_on:
      - postgres
      - redis
      - gotenberg
      - tika
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - $USERDIR/docker/paperless-ng/data:/usr/src/paperless/data
      - /mnt/storage/media/documents:/usr/src/paperless/media
      - /mnt/storage/media/documents/exports:/usr/src/paperless/export
      - /mnt/storage/media/documents/consume:/usr/src/paperless/consume
    env_file: paperless-ng.env
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: (redacted)
      PAPERLESS_DBUSER: (redacted)
      PAPERLESS_DBPASS: (redacted)
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: thecodingmachine/gotenberg
    container_name: gotenberg
    restart: unless-stopped
    networks:
      - lsio
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    container_name: tika
    networks:
      - lsio
    restart: unless-stopped

```
