### DISCUSSION TITLE
Polling SMB share for consuming

### DISCUSSION THREAD

**Discussion by mrrodge2020** [jonaswinkler/paperless-ng#1389] [Support] [answered]
Hi all,

Blown away by this.  Have a setup working with an SMB share on my Windows box but can't understand where to put the PAPERLESS_CONSUMER_POLLING setting.  I've put it in both my docker-compose.env and my docker-compose.yml files (as below) but I still get "[2021-10-14 11:16:26,495] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: " suggesting my config files are being ignored.  Tried killing/restarting the Docker containers.

I know it's not a problem with the share because it works on boot.

config/docker-compose.env:

```
PAPERLESS_TIME_ZONE=Europe/London
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_SECRET_KEY=CbbnothXaQ9y28U0awX9d1tMiqvJnXpjxmHPBYY2ZNYCODH0kOmHV1BOo2zjUYdS
PAPERLESS_CONSUMER_POLLING=30
```

config/docker-compose.yml:

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8123:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/paperless/data:/usr/src/paperless/data
      - /mnt/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/paperless/consumption:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_POLLING: 30
      

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
```
