### DISCUSSION TITLE
after update -> `tika_1 | standard_init_linux.go:228: exec user process caused: exec format error`

### DISCUSSION THREAD

**Discussion by Mannshoch** [jonaswinkler/paperless-ng#1397] [Support]
I followed the update as described in https://paperless-ng.readthedocs.io/en/latest/administration.html#updating-paperless
now I started with `docker-compose up` and got this error from tika

`tika_1 | standard_init_linux.go:228: exec user process caused: exec format error `

Any Idea what went wrong and how I could solve it?

**Comment by TobenderZephyr** [comment]
The container running "Tika" has been updated.
It seems, that either the run command is no longer working, or the container has the wrong binary format. (x86, x64, arm...)

What system is your docker host running on?
Can you output the content of your docker-compose.yml, specifically everything regarding "tika" ?

**Comment by Mannshoch** [comment]
Raspberry Pi 3

docker-compose.yml
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - /mnt/paperlessdata:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/paperlesseingang:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_THREADS_PER_WORKER: 1

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
```

**Comment by TobenderZephyr** [comment]
Unfortunately, Tika is not available as a docker image for your  architecture. It has been published solely for amd64, not for arm.
If you rely on using it you would need to build the image for yourself.

`docker build -t 'apache/tika' github.com/apache/tika-docker`

After using `docker-compose pull` afterwards, it is very likely that it pulls the official image again.

To counter that, download the Dockerfile from the repository I commented above, place it in a folder 'tika' and replace `image: apache/tika` with `build: tika/`

It won't update the image afterwards, but you wouldn't either be able to update Tika without modifying the Dockerfile.

**Reply by Mannshoch** [reply]
simply use  `docker build -t 'apache/tika' github.com/apache/tika-docker` seems not working
`unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/docker-build-git860154987/Dockerfile: no such file or directory`

should I download the repository into a tika called directory beside the docker-compose.yml from paperless or into a tika called directory in my home directory?

Sorry for that but paperless is the first time I work with Docker. Seems that this is a whole new World for me.

**Reply by TobenderZephyr** [reply]
It looks (unlike mentioned on Dockerhub) they moved the Dockerfile into the minimal folder. 
Since I am currently unable to test this command myself: does `docker build -t 'apache/tika' github.com/apache/tika-docker/minimal` work for you?

**Reply by Mannshoch** [reply]
No, seems not work
```
:~ $ docker build -t 'apache/tika' github.com/apache/tika-docker/minimal
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: remote: Not Found
fatal: repository 'https://github.com/apache/tika-docker/minimal/' not found
: exit status 128
```
I also tried this one:
```
:~ $ docker build -t 'apache/tika' github.com/apache/tika-docker/tree/master/minimal
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: 
fatal: repository 'https://github.com/apache/tika-docker/tree/master/minimal/' not found
: exit status 128

```

**Reply by TobenderZephyr** [reply]
Ok, I was just able to test it out myself.
Since the Dockerfile is not in the repository's root directory, the command I mentioned earlier did not work. And you cannot checkout a subdirectory of a repository.
So you would need to either clone the directory 
`git clone https://github.com/apache/tika-docker`
or Download the Dockerfile from the minimal folder
```
mkdir -p tika-docker/minimal
wget https://raw.githubusercontent.com/apache/tika-docker/master/minimal/Dockerfile -O tika-docker/minimal/Dockerfile`
```
In either case the following command should build the new image:
`docker build -t 'tika/docker' tika-docker/minimal`

(I tested the build just until step 3)
```
Sending build context to Docker daemon  5.632kB
Step 1/23 : FROM ubuntu:focal as base
focal: Pulling from library/ubuntu
a39c84e173f0: Pull complete
Digest: sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae288f3322
Status: Downloaded newer image for ubuntu:focal
 ---> d5ca7a445605
Step 2/23 : RUN apt-get update
...
```

Since after a `docker-compose pull` this image is likely to be overwritten by the official docker image from apache (which does not work on ARM devices) it may be better to replace the service 'tika' inside your `docker-compose.yml`.

```
    tika:
      build: ./tika-docker/minimal/
      restart: unless-stopped
```
A `docker-compose build` should be sufficient afterwards, followed by `docker-compose up -d`

**Reply by Mannshoch** [reply]
Error on step 11/23
```
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: key A730529CA355A63E: 15 signatures not checked due to missing keys
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key A730529CA355A63E: public key "Jukka Zitting <jukka@apache.org>" imported
gpg: key 70F09CC6B876884A: public key "Chris Mattmann (CODE SIGNING KEY) <mattmann@apache.org>" imported
gpg: key 5A0DEDEF9740DD55: public key "David Meikle (CODE SIGNING KEY) <dmeikle@apache.org>" imported
gpg: key 606527E6AEA8C6AB: public key "David Meikle (CODE SIGNING KEY) <dmeikle@apache.org>" imported
gpg: key 52414B0B0EB30B07: 2 signatures not checked due to missing keys
gpg: key 52414B0B0EB30B07: public key "David Meikle (CODE SIGNING KEY) <dmeikle@apache.org>" imported
gpg: key 8810BB19D4F10117: public key "Tyler Palsulich <tpalsulich@apache.org>" imported
gpg: key 4A51A45B944FFD51: 3 signatures not checked due to missing keys
gpg: key 4A51A45B944FFD51: public key "Tim Allison (ASF signing key) <tallison@apache.org>" imported
gpg: Total number processed: 7
gpg:               imported: 7
gpg: no ultimately trusted keys found
--2021-10-28 12:07:37--  https://www.apache.org/dyn/closer.cgi/tika/tika-server-.jar?filename=tika//tika-server-.jar&action=download
Resolving www.apache.org (www.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to www.apache.org (www.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-28 12:07:37 ERROR 404: Not Found.

--2021-10-28 12:07:37--  https://www.apache.org/dyn/closer.cgi/tika/tika-server-.jar?filename=tika/tika-server-.jar&action=download
Resolving www.apache.org (www.apache.org)... 151.101.2.132, 2a04:4e42::644
Connecting to www.apache.org (www.apache.org)|151.101.2.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-28 12:07:38 ERROR 404: Not Found.

--2021-10-28 12:07:38--  https://archive.apache.org/dist/tika/tika-server-.jar
Resolving archive.apache.org (archive.apache.org)... 138.201.131.134, 2a01:4f8:172:2ec5::2
Connecting to archive.apache.org (archive.apache.org)|138.201.131.134|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-10-28 12:07:38 ERROR 404: Not Found.

The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get -y install gnupg2 wget     && wget -t 10 --max-redirect 1 --retry-connrefused -qO- https://downloads.apache.org/tika/KEYS | gpg --import     && wget -t 10 --max-redirect 1 --retry-connrefused $NEAREST_TIKA_SERVER_URL -O /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar || rm /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar     && sh -c "[ -f /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar ]" || wget $NEAREST_TIKA_SERVER_URL_OLD -O /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar || rm /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar     && sh -c "[ -f /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar ]" || wget $ARCHIVE_TIKA_SERVER_URL -O /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar || rm /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar     && sh -c "[ -f /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar ]" || exit 1     && wget -t 10 --max-redirect 1 --retry-connrefused $DEFAULT_TIKA_SERVER_ASC_URL -O /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc  || rm /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc     && sh -c "[ -f /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc ]" || wget $DEFAULT_TIKA_SERVER_ASC_URL_OLD -O /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc || rm /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc     && sh -c "[ -f /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc ]" || wget $ARCHIVE_TIKA_SERVER_ASC_URL -O /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc || rm /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc     && sh -c "[ -f /${TIKA_JAR_NAME}-${TIKA_VERSION}.jar.asc ]" || exit 1;' returned a non-zero code: 1


```
You may not able to do something about it because it is not a paperless error. I would report it but https://github.com/apache/tika-docker does not have an Issue tab. So that's may a dead end.

**Reply by TobenderZephyr** [reply]
EDIT:
I had a look again at the Dockerfile, it relies on TIKA_VERSION to be passed along with the build command (it's empty)

1.x
`docker build -t 'apache/tika' tika-docker/minimal --build-arg TIKA_VERSION=1.27 --build-arg TIKA_JAR_NAME=tika-server`

2.x
`docker build -t 'apache/tika' tika-docker/minimal --build-arg TIKA_VERSION=2.1.0 --build-arg TIKA_JAR_NAME=tika-server-standard`

But I'm unaware on how to accomplish that in docker-compose.yml

---
ORIGINAL

You could try one of those 3rd party images, so you would not need to build it yourself.
Some are way outdated:

waratahsolutions/tika-server (3 months)
vmsperandio/tika (1 year)
markusessigde/tika-server (2 years)
in2code/tika (1 day - but this one has no description)


see [Docker Hub](https://registry.hub.docker.com/search?q=tika&type=image&architecture=arm%2Carm64)

**Reply by Mannshoch** [reply]
Thanks, that hint was helpful. I searched in internet and found a way.

I replaced 
```
  tika:
    image: apache/tika
    restart: unless-stopped
```
with 
```
  tika:
    build: 
      context: ../tika-docker/minimal/
      args:
        - TIKA_VERSION=2.1.0
        - TIKA_JAR_NAME=tika-server-standard
    restart: unless-stopped
```
that worked.
