### DISCUSSION TITLE
/data /media folders are empty

### DISCUSSION THREAD

**Discussion by jfml** [jonaswinkler/paperless-ng#1488] [Support] [answered]
Hi, I'm using Paperless-ng via docker and noticed that even though I specified external paths for /media and /data in my docker-compose these are empty as well as their equivalents in /var/lib/docker/volumes/ (eg. paperless-ng_media/_data) Why do these exist? I thought they'd only be created if I do not specify external volume paths?

Document export works, so are the documents stored in the database (paperless-ng_pgdata) or am I doing something wrong?

The relevant portions from my docker-compose:
```
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
   …  
   webserver:
     image: jonaswinkler/paperless-ng:latest
     …
     volumes:
       - /mnt/Docker/Paperless-ng/data:/usr/src/paperless/data
       - /mnt/Docker/Paperless-ng/media:/usr/src/paperless/media
```
Thanks a lot for any tips, loving Paperless-ng so far, can't believe I haven't tried this sooner ^__^
