### DISCUSSION TITLE
I can not get PAPERLESS_ENABLE_HTTP_REMOTE_USER to work

### DISCUSSION THREAD

**Discussion by jacobalberty** [jonaswinkler/paperless-ng#1570] [Support]
My setup has paperless (latest version from git) running in docker with traefik proxying traffic and traefik-forward-auth providing oauth2 authentication and forwarding my username via X-Forwarded-User. I have verified via traefik logs that that header is set in the request and have added that user to paperless:
```
	"request_X-Forwarded-User": "jacob@xxx",
```
I have also added the following environment variables to my paperless docker configuration:
```
     - PAPERLESS_ENABLE_HTTP_REMOTE_USER=1
     - PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME=X-Forwarded-User
     - PAPERLESS_LOGOUT_REDIRECT_URL=/_oauth/logout
```
and finally running `docker-compose exec webserver python manage.py diffsettings | grep REMOTE`
Shows it appears  to be enabled and has the right header selected:
```
ENABLE_HTTP_REMOTE_USER = True  ###
HTTP_REMOTE_USER_HEADER_NAME = 'X-Forwarded-User'  ###
```
I have also tried setting `HTTP_REMOTE_USER_HEADER_NAME` to `HTTP_X_FORWARDED_USER` as per the [documentation for django](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest.META) nothing seems to be working is there something else i'm missing here?

**Comment by jacobalberty** [comment]
So I got this to work by using github.com/tommoulard/htransformation with this as a middleware:

```
http:
  middlewares:
      userhtransform:
        plugin:
          htransformation:
            Rules:
              - Rule:
                Name: 'Header rename'
                Header: 'X-Forwarded-User'
                Value: 'REMOTE_USER'
                Type: 'Rename'
```

it feels less than ideal but it works
