### DISCUSSION TITLE
Scanning documents from iOS (also works on Android)

### DISCUSSION THREAD

**Discussion by s-oliver** [jonaswinkler/paperless-ng#254] [General]
Since I don't have an actual document scanner, I scan most of my day to day documents with my iPhone and like to share my workflow - maybe it helps you or maybe you have better ideas.

Step one is scanning documents as quickly as possible. iOS does have built in capabilities for this, but they are not very convenient, so I opted for a 3rd party app called "Genius Scan" (also available for Android). You do require the plus version (8,99€ at the time of writing) for all share options, but once configured it allows this very quick workflow:
- Open app and hit the large "+" button
- Scan the document
- You're done. It supports auto export to a preconfigured destination where all scanned documents are put automatically, and you can even have the documents deleted immediately after the successful export so they don't clog your phone.
In the scanning process you MAY change every page or the entire document, though I never had to touch the automatic results so far, so this allows me to scan my documents with minimal overhead.

Unfortunately Genius Scan does not support SFTP or FTPS (only the unencrypted FTP) and otherwise almost exclusively cloud services (if I wanted my documents in the cloud, I would not self host paperless..), the last option for encrypted sharing to my paperless server is WebDAV. Of course my documents contain sensitive information, so whenever they're sent over the wire, I'd like that connection to be secure.
Getting the WebDAV service ready is as simple as dropping a `docker-compose.override.yml` in your paperless working directory (next to your `docker-compose.yml`) - or modify your existing one (I have all my modifications of the default services in that file so I don't have to reapply changes every time I upgrade paperless-ng)

```
version: '3.4'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    environment:
      AUTH_TYPE: Basic
      USERNAME: user
      PASSWORD: a-very-long-and-secure-password
    volumes:
      - ./consume:/var/lib/dav
```
Now a `docker-compose up -d` will also start a webdav server next to the other paperless services and expose the "consume" directory. What remains is encryption (see docker hub of bytemark/webdav for their instructions). Since I am running the jwilder nginx-proxy with the let's encrypt companion anyway, I just use it to expose the webdav through a valid and free ssl certificate. So my service descriptions looks like this:
```
version: '3.4'
services:
  webdav:
    image: bytemark/webdav
    restart: always
    environment:
      AUTH_TYPE: Basic
      USERNAME: user
      PASSWORD: a-very-long-and-secure-password
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: docdrop.my.domain.com
      LETSENCRYPT_HOST: docdrop.my.domain.com
    volumes:
      - ./consume:/var/lib/dav
    networks:
      - nginx-proxy_default
networks:
    nginx-proxy_default:
        external: true
```
The `nginx-proxy_default` network is the one that is created by my nginx-proxy service, you may have to adapt it. Having the jwilder nginx-proxy in place already, settings all this up took less than 15 minutes and that includes the download and configuration of the app.
That WebDAV is configured as auto export target in Genius Scan and works very well so far. You could also use a self signed certificate and tell Genius Scan to accept that as well.

Genius Scan also supports OCR, but I have not even tried it for two simple reasons:
- I'm happy with the results of the paperless OCR
- I'd rather have that process run async on my server than synchronously in my scanning workflow and eating up my battery

Why I don't use iOS default tools - every method as major drawbacks:
- Open notes, open any note, tap photo icon, tap "scan document". After the scan, tap to open, use the share button to send via mail / airdrop / ... => many steps and no direct way to forward into paperless, since iOS mails always use inline attachments => no go
- slightly quicker: Open files, navigate to a folder, tap "..." and "scan document", share after scanning. Same sharing problem as the "notes" method above. Also, you end up having all the documents on the phone and need to clean up every once in a while (or delete it straight after sharing)
- In the mails app you can directly scan documents as attachments, but still have to type your mail address every time and possibly a subject if your paperless email filter is configured so, and eventually you end up with the issue, that iOS attachments are always inline => also no go

How a
