### DISCUSSION TITLE
Multiple instances of paperless-ng docker

### DISCUSSION THREAD

**Discussion by axlgit** [jonaswinkler/paperless-ng#916] [Support]
Hi,

I would like to run two instances of Paperless-ng on the some docker host, business/personal. I customized docker-compose.yml but I have a couple of questions.
First of all, here the diff's output between the `docker-compose.yml` I used for the first installation and the `docker-compose.yml` I would use for the second installation:

```
--- docker-compose.yml  2021-04-14 13:30:31.759978807 +0100
+++ docker-compose.yml.bkp      2021-04-14 13:27:02.681433768 +0100
@@ -40,9 +40,9 @@
     image: postgres:13
     restart: unless-stopped
     volumes:
-      - pgdata:/var/lib/paperless_biz/postgresql/data
+      - pgdata:/var/lib/postgresql/data
     environment:
-      POSTGRES_DB: paperless_biz
+      POSTGRES_DB: paperless
       POSTGRES_USER: paperless
       POSTGRES_PASSWORD: paperless

@@ -55,17 +55,17 @@
       - gotenberg
       - tika
     ports:
-      - 8001:8001
+      - 8000:8000
     healthcheck:
-      test: ["CMD", "curl", "-f", "http://localhost:8001"]
+      test: ["CMD", "curl", "-f", "http://localhost:8000"]
       interval: 30s
       timeout: 10s
       retries: 5
     volumes:
-      - data:/usr/src/paperless_biz/data
-      - media:/usr/src/paperless_biz/media
-      - ./export:/usr/src/paperless_biz/export
-      - /home/axl/paperless-ng_biz/consume:/usr/src/paperless_biz/consume
+      - data:/usr/src/paperless/data
+      - media:/usr/src/paperless/media
+      - ./export:/usr/src/paperless/export
+      - /home/axl/paperless-ng/consume:/usr/src/paperless/consume
     env_file: docker-compose.env
     environment:
       PAPERLESS_REDIS: redis://broker:6379
```

My questions:

1) in the doc (latest, 1.4.0) I read
Replace the part BEFORE the colon with a local directory of your choice:

`- /home/jonaswinkler/paperless-inbox:/usr/src/paperless/consume`

Don’t change the part after the colon or paperless wont find your documents.

I guess I have to change also the second part but I'm told not to. How to achieve that? (no problem in diggging the code and change it by myself if I'm told where to do that)

2) What about tika, gotemberg, and redis components?
```
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
```

Do I have to change also that part? Is it sufficient to choose a different port than those I chose for the firtst installation?

Sorry for the simple questions but it's my first time I'm trying to run multiple instances of Paperless and it's a bit that I'm not touching docker in depth.

Thanks, Axl

**Comment by axlgit** [comment]
I hope my previous request was not too intimidating with the diff output! :-)

I would just need to know if concurrrent instances of paperless can run on the same docker hub or if it is advised to run them on different hubs. Any advice/comment will be much appreciated!

Many thanks in advance,

Axl

**Comment by ovidioruzzier** [comment]
Hi all,

has this request been answered? I'm in the same situation and I tried to install two instances on docker without any success.
@axlgit: have you managed to achieve your goal?

Has anybody else willing to give a hint or at least tell if this is possible or not?

TIA, Ovidio

**Reply by axlgit** [reply]
Hi Ovidio,

nope, eventually I created a seperate docker instance. It's a pity that I had to fall back (as to paperless) to the method 1 application : 1 virtual machine.

Sorry,

Axl

**Comment by TheFehr** [comment]
> ```
> --- docker-compose.yml  2021-04-14 13:30:31.759978807 +0100
> +++ docker-compose.yml.bkp      2021-04-14 13:27:02.681433768 +0100
> @@ -40,9 +40,9 @@
>      image: postgres:13
>      restart: unless-stopped
>      volumes:
> -      - pgdata:/var/lib/paperless_biz/postgresql/data
> +      - pgdata:/var/lib/postgresql/data
>      environment:
> -      POSTGRES_DB: paperless_biz
> +      POSTGRES_DB: paperless
>        POSTGRES_USER: paperless
>        POSTGRES_PASSWORD: paperless
> 
> @@ -55,17 +55,17 @@
>        - gotenberg
>        - tika
>      ports:
> -      - 8001:8001
> +      - 8000:8000
>      healthcheck:
> -      test: ["CMD", "curl", "-f", "http://localhost:8001"]
> +      test: ["CMD", "curl", "-f", "http://localhost:8000"]
>        interval: 30s
>        timeout: 10s
>        retries: 5
>      volumes:
> -      - data:/usr/src/paperless_biz/data
> -      - media:/usr/src/paperless_biz/media
> -      - ./export:/usr/src/paperless_biz/export
> -      - /home/axl/paperless-ng_biz/consume:/usr/src/paperless_biz/consume
> +      - data:/usr/src/paperless/data
> +      - media:/usr/src/paperless/media
> +      - ./export:/usr/src/paperless/export
> +      - /home/axl/paperless-ng/consume:/usr/src/paperless/consume
>      env_file: docker-compose.env
>      environment:
>        PAPERLESS_REDIS: redis://broker:6379
> ```
One mistake I can see for sure is, that you changed the healthcheck test and your port internally and externally.


The following is what I added to my existing docker-compose file. And it works perfectly.
Obviously the volumes would need to be added to the existing volumes configured.
```
  broker2nd:
    image: redis:6.0
    restart: always
    networks:
      - paperless-internal

  db2nd:
    image: postgres:13
    restart: always
    volumes:
      - pgdata2nd:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - paperless-internal

  webserver2nd:
    image: jonaswinkler/paperless-ng:latest
    restart: always
    depends_on:
      - db
      - broker
    ports: 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data2nd:/usr/src/paperless/data
      - media2nd:/usr/src/paperless/media
      - ./2nd/export:/usr/src/paperless/export
      - ./2nd/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker2nd:6379
      PAPERLESS_DBHOST: db2nd
    ports:
      - 8001:8000
    networks:
      - paperless-internal

volumes:
  data2nd:
  media2nd:
  pgdata2nd: 
```

I did not try using the same db or redis container. Might work if we could configure it correctly on the paperless side. I did not investigate that further.
