### DISCUSSION TITLE
Documents are not consumed from SMB-Share

### DISCUSSION THREAD

**Discussion by mikedolx** [jonaswinkler/paperless-ng#938] [Support] [answered]
Hi,

i have recently setup an instance of paperless-ng in a vritual machine (ubuntu 20 LTS) in my homelab environment. It seems i can't get the default consumption task up and running. When i copy a PDF into the consume folder, paperless neither shows the document in the frontend nor is the document deleted from the folder. 

I used the `install-paperless-ng.sh` for installation together with docker and docker compose. I choose to mount all directories that paperless uses on my NAS, therefore i have created the following folder in the VM for paperless:

```
paperless@paperless-ng:~$ ll /mnt/
total 8
drwxr-xr-x  6 root    root    4096 Apr 14 18:52 ./
drwxr-xr-x 20 root    root    4096 Apr 14 12:30 ../
drwxrwx---  2 paperless paperless    0 Apr 18 23:43 config/
drwxrwx---  2 paperless paperless    0 Apr 19 07:40 consume/
drwxrwx---  2 paperless paperless    0 Apr 18 21:08 data/
drwxrwx---  2 paperless paperless    0 Apr 19 07:37 media/
```

### /etc/fstab

```
//hostname-of-my-nas/paperless-ng/media   /mnt/media   cifs    rw,vers=3.0,credentials=/home/paperless/.smbcred,uid=paperless,gid=paperless,file_mode=0770,dir_mode=0770   0   0
//hostname-of-my-nas/paperless-ng/config   /mnt/config   cifs    rw,vers=3.0,credentials=/home/paperless/.smbcred,uid=paperless,gid=paperless,file_mode=0770,dir_mode=0770   0   0
//hostname-of-my-nas/paperless-ng/data   /mnt/data   cifs    rw,vers=3.0,credentials=/home/paperless/.smbcred,uid=paperless,gid=paperless,file_mode=0770,dir_mode=0770   0   0
//hostname-of-my-nas/public/paperless   /mnt/consume   cifs   rw,vers=3.0,credentials=/home/paperless/.smbcred,uid=paperless,gid=paperless,file_mode=0770,dir_mode=0770   0   0
```

I checked logs but couldn't get any errors. I logged into the container and listed the content of /usr/src/paperless/consume. I can see the three pdfs i had copied there for testing. I can also create new files and write to them.

```
root@0346aa47fd65:/usr/src/paperless/consume# ls -l
total 392
-rwxrwx--- 1 paperless paperless  31343 Feb 22 21:35 'test 1.pdf'
-rwxrwx--- 1 paperless paperless  31173 Feb 22 21:35 'test 2.pdf'
-rwxrwx--- 1 paperless paperless 299740 Apr 19 07:07  GW_Rechnung_02.04.2021.pdf
```

I played around with the user permissions for the webserver container. I added the following user and group ID to the docker-compose.yml

```
paperless@paperless-ng:~$ grep 1000 /etc/passwd
paperless:x:1000:1000:paperless:/home/paperless:/bin/bash
```

That seem to do the trick, but i got random restarts of the container, where the docker logs were claiming, that the user is not in the sudoers list.

-> Am i missing something? Any hint is appreciated!

Thanks,

BR

Michael

* * *

The configuration files are below:

## .env file

COMPOSE\_PROJECT\_NAME=paperless

## docker-compose.env

```
PAPERLESS_TIME_ZONE=Europe/Berlin
PAPERLESS_OCR_LANGUAGE=deu
PAPERLESS_SECRET_KEY=***
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true
```

### docker-compose.yml

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    user: 1000:1000
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 80:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/data:/usr/src/paperless/data
      - /mnt/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
```

## docker version

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## docker-compose version

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
