### ISSUE TITLE
[Q] Paperless-NG behind Traefik reverse proxy (everything Docker)

### ISSUE THREAD

**Issue by Pinback22** [jonaswinkler/paperless-ng#1148]
Hey,
I'm trying to publish Paperless-NG via Traefik Reverse Proxy. 
- Added the docker container "paperless_webserver_1" as a service to Traefik
- Traefik fetches the certificate from Lets Encrypt
- redirects the service to port 8000 in the docker container

If I manually map the container port 8000 to something like 8088, the UI comes up when hitting "%servername:8088". 
However with Traefik no ports should need to be published manually. 
I've read something about websockets? The Traefik docs tell me that websockets don't need to be configured and are enabled. 
I'm a bit lost here. Anybody had more success?

**Comment by shamoon** [comment]
Hey @Pinback22, this should probably be a 'discussion' not an 'issue'.

Ive had this working for a long time, here's the relevant section of my compose file, wonder if it clarifies anything for you:

```
  paperless:
    image: jonaswinkler/paperless-ng:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-redis
    ports:
      - 8000:8000
    networks:
      - macvlan_network
      - traefik_proxy
    labels:
      - traefik.http.routers.paperless.rule=Host(`paperless.mydomainname.com`)
      - traefik.http.routers.paperless.tls.certresolver=le
      - traefik.http.routers.paperless.entrypoints=websecure
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      - traefik.http.routers.paperless.middlewares=chain-authelia
      - traefik.docker.network=traefik_proxy
    volumes:
      ...
    environment:
      ...
```
