### ISSUE TITLE
[Help Needed] How to Connect to local postgres database from docker image

### ISSUE THREAD

**Issue by jeroen7s** [jonaswinkler/paperless-ng#1271]
I'm trying to connect paperless-ng to a local postgres installation, but I keep getting errors saying it can't connect.
Not that experienced with docker so I'm not sure how I can fix this
my compose.yml looks like this:
``` yml
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - 8010:8000
      - 5432:5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /media/data/paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: 172.17.0.1
      PAPERLESS_DPPORT: 5432
      PAPERLESS_DBUSER: <postgres-username>
      PAPERLESS_DBPASS: <postgres-pass>
      PAPERLESS_TIKA_ENABLED: 0

volumes:
  data:
  media:
  pgdata:
```
the DB_HOST ip is what I found for docker when running `ip a`
I also tried `localhost` and `127.0.0.1` as values here, but none of them seem to work
