### ISSUE TITLE
Starting to use paperless, added two files are missing

### ISSUE THREAD

**Issue by balajeek** [jonaswinkler/paperless-ng#1278]
I installed paperless-ng on docker with docker-compose on my qnap, here the docker-compose

```
  paperless:
    image: jonaswinkler/paperless-ng:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8600:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /share/Container/paperless/export:/usr/src/paperless/export
      - /share/Container/paperless/consume:/usr/src/paperless/consume
    env_file: /share/Container/paperless/docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
```

volumes on the docker-compose is also set
```
volumes:
  data:
  media:
  pgdata:
```

I setup and created user and logged in, added a test document from the dashboard by uploading it, it did its thing and showed me the file in the dashboard, searched for some text and seem to find it.

Next i drag & drop another test file from a folder to paperless consume folder (as per the documentation this is the folder being watched for new files). Immediately paperless found the file and started processing and i am able to see/search in dashboard.

According to the documentation, the file that i drag & dropped should be there in the consume folder or at least if its archieved then it should be in the media folder.  I don't see them, so far the two file i added i am able to see only from dashboard but not anywhere the physical folder locations (/share/Container/paperless/ in my case)

What am I doing wrong.  I would like to know before i move all my documents.

**Relevant information**
 - QNAP TS-451 container running paperless:
 - chrome or safari browser
 - latest Version 
 - docker
