### ISSUE TITLE
[BUG] webserver hangs on " Waiting for PostgreSQL to start..."

### ISSUE THREAD

**Issue by laeckerv** [jonaswinkler/paperless-ng#1287]
**Describe the bug**
Installed paperless via Portainer and the [docker-compose](https://github.com/jonaswinkler/paperless-ng/blob/master/docker/compose/docker-compose.portainer.yml). (adapted the volumes properly)

All the container, the network and the volumes were created properly. The broker and the db also start up properly. Just the webserver hangs on "Waiting for PostgreSQL to start...".

```
Paperless-ng docker container starting...,
Mapping UID and GID for paperless:paperless to 1026:100,
Creating directory ../data/index,
Creating directory ../media/documents,
Creating directory ../media/documents/originals,
Creating directory ../media/documents/thumbnails,
Creating directory /tmp/paperless,
Adjusting permissions of paperless files. This may take a while.,
Waiting for PostgreSQL to start...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Attempt 1 failed! Trying again in 5 seconds...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Attempt 2 failed! Trying again in 5 seconds...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Attempt 3 failed! Trying again in 5 seconds...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Attempt 4 failed! Trying again in 5 seconds...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Unable to connect to database.,
Paperless-ng docker container starting...,
Creating directory /tmp/paperless,
Adjusting permissions of paperless files. This may take a while.,
Waiting for PostgreSQL to start...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Attempt 1 failed! Trying again in 5 seconds...,
/sbin/docker-prepare.sh: connect: Connection timed out,
/sbin/docker-prepare.sh: line 16: /dev/tcp/db/5432: Connection timed out,
Attempt 2 failed! Trying again in 5 seconds...
```

![image](https://user-images.githubusercontent.com/1636489/132257566-be6baea1-9ff2-420b-9aef-df239bc31067.png)

**To Reproduce**
1. Install paperless via the portainer docker-compose.yml
2. Wait for containers to be created and started
3. See log of webserver container

**Relevant information**
```
Docker version 20.10.3, build b35e731
docker-compose version 1.28.5, build 1bbbad71
```

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /volume1/docker/paperless/export:/usr/src/paperless/export
      - /volume1/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      USERMAP_UID: 1026
      USERMAP_GID: 100

volumes:
  data:
  media:
  pgdata:
```
