### ISSUE TITLE
[BUG] Sometimes not loading documents in doc view

### ISSUE THREAD

**Issue by alexandzors** [jonaswinkler/paperless-ng#1325]
**Describe the bug**
When using the web ui. Non tagged docs / all docs not visible unless I go into already made doc types and view docs associated with said type. Sometimes they appear after coming in and out of the tab a few times however most of the time they are not visible.

**To Reproduce**
1. Install Paperless-ng 1.5.0 via Docker with no docker managed volumes using post db
2. Add documents to consume directory
3. Consume docs
4. Login to web ui
5. Click documents on left menu

**Expected behavior**
Documents are visible when viewing all docs or filtering based on tags/doc types.

**Screenshots**
![image](https://user-images.githubusercontent.com/25626115/133907115-0d46093a-922e-4cbd-8b83-163c01faf541.png)
![image](https://user-images.githubusercontent.com/25626115/133907273-b3da7cf1-89af-40dc-9bca-06adb5c722c3.png)
![image](https://user-images.githubusercontent.com/25626115/133907276-f18da3b6-fe72-4728-894d-dcf93e3b6455.png)

**Webserver logs**
Logs look fine. No errors are vis and I can see paperless-ng consuming and changing metadata for docs.

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu Server 20.04 VM in Hyper-V.
 - Browser: Edge 93.0.961.52 (Official build)
 - Version 1.5.0
 - Installation method: docker + post
 - Docker Engine Version: 20.10.8
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

```yaml
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /opt/docker/paperless/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ***
  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/docs/paperless/data:/usr/src/paperless/data
      - /mnt/docs/paperless:/usr/src/paperless/media
      - /mnt/docs/paperless/export:/usr/src/paperless/export
      - /mnt/docs/paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1
  tika:
    image: apache/tika
    restart: unless-stopped
```
```env
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000
# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# language used for OCR.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
#PAPERLESS_OCR_LANGUAGES=tur ces
###############################################################################
# Paperless-specific settings                                                 #
###############################################################################
# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.
# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
PAPERLESS_SECRET_KEY=****
# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=America/New_York
# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng
PAPERLESS_DBPASS=****
PAPERLESS_CONSUMER_POLLING=10
```
