### ISSUE TITLE
[BUG] 1.5.0 Task Queue Not Working for Consumption

### ISSUE THREAD

**Issue by mrrodge2020** [jonaswinkler/paperless-ng#1390]
**Describe the bug**
In-use files (still being written by scanner but discovered by paperless) state they're added to the task queue but then never get processed.  Other documents get discovered and processed after this and the stalled documents get processed after a reboot.

**To Reproduce**
Scan a document to an SMB share for consumption.  Ensure it gets discovered by paperless before the scanner has finished writing the file.

**Expected behavior**
Would expect the task queue to process the file later, allowing time for the scanner to release the file.

**Screenshots**
N/A

**Webserver logs**
```
[2021-10-14 13:14:17,445] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/src/../consume/scan_20211014120914.pdf to remain unmodified

[2021-10-14 13:14:22,457] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/src/../consume/scan_20211014120914.pdf to the task queue.
```

**Relevant information**
 - Debian 11
 - Browser [Firefox]
 - Version [e.g. 1.5.0]
 - Installation method: [Docker]

-docker-compose.yml:

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8123:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/paperless/data:/usr/src/paperless/data
      - /mnt/paperless/media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - /mnt/paperless/consumption:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_CONSUMER_POLLING: 30
      

  gotenberg:
    image: thecodingmachine/gotenberg
    restart: unless-stopped
    environment:
      DISABLE_GOOGLE_CHROME: 1

  tika:
    image: apache/tika
    restart: unless-stopped

volumes:
  data:
  media:
  pgdata:
```
