### ISSUE TITLE
[BUG] tesseract timeouts not propagated to Logs or Dashboard

### ISSUE THREAD

**Issue by mbwgh** [jonaswinkler/paperless-ng#1411]
**Describe the bug**
When scanning a rather large pdf (car insurance documents, 33MB with some corporate background pattern on each page), the `ocrmypdf` step takes a long time to complete. I was finally able to get it to complete by adding
```
  PAPERLESS_OCR_USER_ARGS: '{"tesseract-timeout": 900}'
```
in the `docker-compose` file.

While these kind of files might be pathological cases, tesseract do not manifest themselves in the frontend.
The dashboard will either be stuck at "processing" or won't show an indication at all that there are pending or failed jobs after refreshing the page.
The "Logs" panel will look like this:
![2021-10-25-003041_1565x455_scrot](https://user-images.githubusercontent.com/28275377/138615546-1b5ca092-514c-42a6-a5d0-13c8af749614.png)
Here you can see that I tried to scan the same document twice, after the first attempt silently failed.

The output of `docker-compose logs -f <paperless-webserver>` barely hints at the problem:
```
services-paperless-webserver-1  | 23:20:06 [Q] INFO Q Cluster mike-east-steak-friend running.
services-paperless-webserver-1  | 23:21:57 [Q] INFO Enqueued 1
services-paperless-webserver-1  | 23:21:57 [Q] INFO Process-1:1 processing [CCF23102021_0001.pdf]
services-paperless-webserver-1  | [2021-10-24 23:21:57,508] [INFO] [paperless.consumer] Consuming CCF23102021_0001.pdf
services-paperless-webserver-1  | 23:21:58 [Q] INFO Enqueued 1
services-paperless-webserver-1  | 23:21:58 [Q] INFO Process-1:2 processing [CCF23102021_0003.pdf]
services-paperless-webserver-1  | [2021-10-24 23:21:58,790] [INFO] [paperless.consumer] Consuming CCF23102021_0003.pdf
services-paperless-webserver-1  | [2021-10-24 23:22:05 +0200] [35] [CRITICAL] WORKER TIMEOUT (pid:38)
services-paperless-webserver-1  | [2021-10-24 23:22:06 +0200] [35] [WARNING] Worker with pid 38 was terminated due to signal 9
services-paperless-webserver-1  | 23:24:08 [Q] INFO Enqueued 1
services-paperless-webserver-1  | 23:24:08 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
services-paperless-webserver-1  | [2021-10-24 23:25:14,041] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:30:19,626] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:33:36,258] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:33:42,048] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | 23:34:15 [Q] INFO Enqueued 1
services-paperless-webserver-1  | 23:34:15 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
services-paperless-webserver-1  | [2021-10-24 23:35:51,547] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:36:33,856] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:37:13,840] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:39:19,053] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:40:11,555] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | 23:44:22 [Q] INFO Enqueued 1
services-paperless-webserver-1  | 23:44:22 [Q] INFO Process-1 created a task from schedule [Check all e-mail accounts]
services-paperless-webserver-1  | [2021-10-24 23:46:02,948] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:48:38,461] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
services-paperless-webserver-1  | [2021-10-24 23:50:23,036] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
services-paperless-webserver-1  | [2021-10-24 23:50:27,743] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:50:48,256] [ERROR] [ocrmypdf._exec.tesseract] [tesseract] Error during processing.
services-paperless-webserver-1  | [2021-10-24 23:51:28,639] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | [2021-10-24 23:51:33,892] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
services-paperless-webserver-1  | 23:52:18 [Q] WARNING reincarnated worker Process-1:1 after timeout
services-paperless-webserver-1  | 23:52:18 [Q] INFO Process-1:5 ready for work at 1159
services-paperless-webserver-1  | 23:52:18 [Q] INFO Process-1:5 processing [earth-black-romeo-lemon]
services-paperless-webserver-1  | 23:52:18 [Q] INFO Process-1:5 stopped doing work
services-paperless-webserver-1  | 23:52:18 [Q] INFO Processed [earth-black-romeo-lemon]
services-paperless-webserver-1  | 23:52:18 [Q] INFO recycled worker Process-1:5
services-paperless-webserver-1  | 23:52:18 [Q] INFO Process-1:6 ready for work at 1161
services-paperless-webserver-1  | 23:52:18 [Q] INFO Process-1:6 processing [social-fourteen-music-venus]
services-paperless-webserver-1  | 23:52:18 [Q] INFO Process-1:6 stopped doing work
services-paperless-webserver-1  | 23:52:18 [Q] INFO Processed [social-fourteen-music-venus]
services-paperless-webserver-1  | 23:52:19 [Q] INFO recycled worker Process-1:6
services-paperless-webserver-1  | 23:52:19 [Q] INFO Process-1:7 ready for work at 1163
services-paperless-webserver-1  | 23:52:19 [Q] INFO Process-1:7 processing [pasta-nebraska-grey-harry]
services-paperless-webserver-1  | 23:52:19 [Q] INFO Process-1:7 stopped doing work
services-paperless-webserver-1  | 23:52:19 [Q] INFO Processed [pasta-nebraska-grey-harry]
services-paperless-webserver-1  | 23:52:19 [Q] INFO recycled worker Process-1:7
services-paperless-webserver-1  | 23:52:19 [Q] INFO Process-1:8 ready for work at 1165
services-paperless-webserver-1  | 23:52:20 [Q] WARNING reincarnated worker Process-1:2 after timeout
```

**To Reproduce**
Try to scan a demanding document with default or tesseract timeout.

**Expected behavior**
Timeouts should be visible at least when looking into the logs. The dashboard, or via notification, would be even better.

**Relevant information**
 - Host OS of the machine running paperless: Arch Linux
 - Browser: Mozilla Firefox 93.0
 - Version: 1.5.0
 - Installation method: docker

Excerpt from `docker-compose.yml`:
```yaml
paperless-broker:
    image: redis:6.0
    restart: unless-stopped

  paperless-webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - paperless-broker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 0
    volumes:
      - ./resources/paperless/data:/usr/src/paperless/data
      - ./resources/paperless/media:/usr/src/paperless/media
      - ./resources/paperless/export:/usr/src/paperless/export
      - ./resources/paperless/consume:/usr/src/paperless/consume
    env_file: ./resources/paperless/docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_FORCE_SCRIPT_NAME: /internal/paperless
```
