### ISSUE TITLE
[BUG] Progression bar stuck

### ISSUE THREAD

**Issue by Keiishu** [jonaswinkler/paperless-ng#1573]
**Describe the bug**
Whenever I try to upload a document from the web interface, the progression bar gets stuck at "Upload complete, waiting...".
No status is reported beyond that, whether it's a success or an error, with the only exception being when the file type is not supported.

**To Reproduce**
1. Go to the web interface
2. Upload a supported file with "Upload new documents"
3. Observe the progression bar not going further than "Upload complete, waiting..."

**Expected behavior**
The progression bar reflecting the current status of the consumer/worker.

**Screenshots**
![image](https://user-images.githubusercontent.com/28761304/150690215-5ad1784a-dbc0-48a9-88e1-4b3f77f845fb.png)

**Webserver logs**
```
(...)
18:16:27 [Q] INFO Process-1:15 processing [CV.pdf]
18:16:27 [Q] INFO Enqueued 1
[2022-01-23 18:16:30,209] [INFO] [paperless.consumer] Consuming CV.pdf
[2022-01-23 18:16:58,588] [INFO] [paperless.consumer] Document 2001-09-03 CV consumption finished
18:16:58 [Q] INFO Process-1:15 stopped doing work
18:16:58 [Q] INFO recycled worker Process-1:15
18:16:58 [Q] INFO Process-1:17 ready for work at 1835
18:16:59 [Q] INFO Processed [CV.pdf]
(...)
```

**Relevant information**
 - Paperless-ng 1.5.0 on Docker 20.10.3, on a Synology NAS (DS218+ – DSM 7.0.1)
 - Tried on Firefox 96.0.2 and Brave 1.34.81
 - Tried with and without my reverse proxy

<details>
<summary>docker-compose.yml</summary>

```yml
version: "3.8"
services:
  paperless-ng:
    image: jonaswinkler/paperless-ng
    container_name: Paperless
    depends_on:
      - redis
      - gotenberg
      - tika
    environment:
      USERMAP_UID: <redacted>
      USERMAP_GID: 100
      TZ: Europe/Brussels
      PAPERLESS_TIME_ZONE: Europe/Brussels
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_SECRET_KEY: <redacted>
      PAPERLESS_OCR_LANGUAGES: fra eng
      PAPERLESS_OCR_LANGUAGE: fra+eng
      PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD: 9
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    volumes:
      - <redacted>
    ports:
      - 8100:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://<redacted>:8100"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - paperless-ng
  redis:
    image: redis:4-alpine
    container_name: Paperless-Redis
    environment:
      - TZ=Europe/Brussels
    command: redis-server --bind redis --port 6379 --maxmemory 64M --maxmemory-policy volatile-lru
    restart: unless-stopped
    networks:
      - paperless-ng
  gotenberg:
    image: thecodingmachine/gotenberg:6
    container_name: Paperless-Gotenberg
    environment:
      TZ: Europe/Brussels
      DISABLE_GOOGLE_CHROME: 1
      MAXIMUM_WAIT_TIMEOUT: 300.0
      DEFAULT_WAIT_TIMEOUT: 300.0
    command: gotenberg --api-port=3000 --api-process-timeout=300 --log-level=debug
    restart: unless-stopped
    networks:
      - paperless-ng
  tika:
    image: apache/tika:1.27-full
    container_name: Paperless-Tika
    environment:
      TZ: Europe/Brussels
    restart: unless-stopped
    networks:
      - paperless-ng
networks:
  paperless-ng:
    name: paperless-ng
```

</details>
