### ISSUE TITLE
Documents not found "over night"

### ISSUE THREAD

**Issue by ostpol** [jonaswinkler/paperless-ng#421]
Hi, I freshly moved to paperless-ng and it looks great!

Sadly the webinterface can't find the documents anymore "over night":

```
GET /api/documents/126/preview/

HTTP 404 Not Found
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Nicht gefunden."
}
```

This applies to every document and the thumbnails aren't displayed too. The files are still available in the directories. 

I am running paperless-ng in Docker 20.10.2 on Ubuntu 20.04.1.

**Comment by ostpol** [comment]
I think it's related to Docker:

```
root@3aadfd8f77db:/usr/src/paperless/src# ls -ll /usr/src/paperless/media/documents/originals/
total 0
```

The container can't see the files in the hosts directories.

```
/media/documents/inbox | /usr/src/paperless/consume
/media/documents/store | /usr/src/paperless/data
/media/documents/export | /usr/src/paperless/export
/media/documents/media | /usr/src/paperless/media
```

```
tony@server:/media/documents$ ls -ll /media/documents/
total 0
drwxr-xr-x 2 tony tony 0 Mär  5  2020 archive
drwxr-xr-x 2 tony tony 0 Jan 22 18:53 export
drwxr-xr-x 2 tony tony 0 Jan 24 09:15 inbox
drwxr-xr-x 2 tony tony 0 Jan 23 08:44 media
drwxr-xr-x 2 tony tony 0 Jan 23 09:41 store
drwxr-xr-x 2 tony tony 0 Jan 22 18:38 tmp
tony@server:/media/documents$ id
uid=1000(tony) gid=1000(tony) groups=1000(tony)
```

Nothing suspicious (for me) and nothing has changed since I initially configured everything yesterday. I'm not that deep into Docker, so im sure that I'm missing something.

**Comment by jonaswinkler** [comment]
Please post either your docker compose file or the commands you use for starting the container.

**Comment by ostpol** [comment]
```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: unless-stopped

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - 8008:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /media/documents/store:/usr/src/paperless/data
      - /media/documents/media:/usr/src/paperless/media
      - /media/documents/export:/usr/src/paperless/export
      - /media/documents/inbox:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
```
