### ISSUE TITLE
[BUG] Incorrect thumbnail on documents view

### ISSUE THREAD

**Issue by rssfed23** [jonaswinkler/paperless-ng#520]
**Describe the bug**
I was doing a bulk import into a new paperless instance, and when browsing the documents view and previewing some documents I happen to notice that some have the incorrect thumbnail.
It seems to be incorrect on around 10% of the documents I've checked so far
Only the thumbnail image is incorrect. The filename and other metadata reflect the "opened" PDF.

Is there a command I can run to re-generate the thumbnails to see if it happens again?

I did try a complete wipe and reinstall of paperless but the same thing happens again, although of note it's different files that it happens to with different thumbnails than before. Very odd.

**To Reproduce**
Import files via the consume folder
Browse documents view. Note some thumbnails are not correct.

**Expected behavior**
The thumbnails to be correct

**Screenshots**
I've created a video which I hope shows the issue clearly where you can see the thumbnail does not match the first page of the document when it's opened fully (they're completely different document thumbnails from other files):
(the data visible within the documents is all very old or out of date/inaccurate so happy to share these).

https://user-images.githubusercontent.com/12484127/107422518-0ce7ca80-6b13-11eb-965c-d2d48ac2beed.mp4

**Webserver logs**
I'm not seeing any significant errors in the logs. The only kind of errors aside from duplicates I can see are:
```
webserver_1  | [2021-02-09 19:27:50,547] [INFO] [paperless.consumer] Consuming 12ba2a84-e495-428d-b751-1edb613d6657.pdf
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
webserver_1  |    **** Error: stream Length incorrect.
webserver_1  |                Output may be incorrect.
```

**Relevant information**
 - Host OS of the machine running paperless: Ubuntu 20.04
 - Browser: Chrome. Also happens on Safari and Firefox
 - Installation method: Docker compose with Tika
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`:
 My env vars:
```
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_TIME_ZONE: "Europe/London"
      PAPERLESS_OCR_MODE: redo
      PAPERLESS_TASK_WORKERS: 3
      PAPERLESS_THREADS_PER_WORKER: 4
      #      PAPERLESS_CONSUMER_POLLING: 15
      PAPERLESS_IGNORE_DATES: "1990-06-26"
      PAPERLESS_AUTO_LOGIN_USERNAME: rob
      PAPERLESS_FILENAME_FORMAT: "{correspondent}/{created_year}/{title}"
```
