### ISSUE TITLE
[BUG] Cannot change base href

### ISSUE THREAD

**Issue by ahaw** [jonaswinkler/paperless-ng#816]
My docker compose file: 

=> Don't remove the [BUG] prefix from the title.
-->

**Describe the bug**
I'm using paperless with using caddy reverse proxy I cannot get it working correctly because when I open: 
https://example.com/paperlessng/dashboard im being redirected by paperless-ng server to:
https://example.com/accounts/login/?next=/paperlessng/dashboard

If I run it locally (192.168.X.X.) I can log in using 192.168.0.2/accounts/login/ and after that I'm being redirected to 192.168.0.2/paperlessng/accounts/login/.
What could be important is that '/accounts/login/' page doesn't have <base href="/paperlessng/"> node but the 'paperlessng/dashboard' has it.

**To Reproduce**
Create paperless docker container using PAPERLESS_FORCE_SCRIPT_NAME option. 

**Expected behavior**
During redirection base dir (/paperlessng) should not be stripped and I should be able to open https://example.com/paperlessng/accounts/login/?next=/paperlessng/dashboard

**Relevant information**
Caddy2 config
```
 redir /paperlessng /paperlessng/
  handle /paperlessng/* {
    reverse_proxy paperlessng:8000 {
       header_up X-Real-IP {remote_host}
    }
  }
```

Docker compose
```
 paperless:
  image: jonaswinkler/paperless-ng:latest
  container_name: paperlessng
  hostname: paperlessng
  restart: unless-stopped
  depends_on:
   - paperlessng_db
   - broker
  ports:
   - 8000:8000
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8000"]
   interval: 30s
   timeout: 10s
   retries: 5
  volumes:
   - ./paperlessng/paperless/data:/usr/src/paperless/data
   - ./paperlessng/paperless/media:/usr/src/paperless/media
   - ./paperlessng/paperless/export:/usr/src/paperless/export
   - ./paperlessng/paperless/consume:/usr/src/paperless/consume
  environment:
   PAPERLESS_REDIS: redis://broker:6379
   PAPERLESS_DBHOST: paperlessng_db
   COMPOSE_PROJECT_NAME: paperless
   PAPERLESS_ALLOWED_HOSTS: "example.com,localhost,192.168.0.2"
   PAPERLESS_CORS_ALLOWED_HOSTS: "https://example.com,http://localhost,http://192.168.0.2"
   PAPERLESS_SECRET_KEY: "secret"
   PAPERLESS_FORCE_SCRIPT_NAME: "/paperlessng/"

```
