### ISSUE TITLE
Operation Not Permitted

### ISSUE THREAD

**Issue by bwoodworth** [jonaswinkler/paperless-ng#85]
I'm having a problem using a NFS share for the data, media and comse directories.  After installing using the docker-compose.yml file I am just getting this output:

> chown: changing ownership of '../export': Operation not permitted
> chown: changing ownership of '../media/documents/thumbnails': Operation not permitted
> chown: changing ownership of '../media/documents/originals': Operation not permitted
> chown: changing ownership of '../media/documents': Operation not permitted
> chown: changing ownership of '../media': Operation not permitted
> chown: changing ownership of '../consume': Operation not permitted
> chown: changing ownership of '../data/db.sqlite3': Operation not permitted
> chown: changing ownership of '../data/index': Operation not permitted
> chown: changing ownership of '../data/db.sqlite3.migration': Operation not permitted
> chown: changing ownership of '../data': Operation not permitted

**Comment by jonaswinkler** [comment]
Please give me some more information.

- Did you configure any additional settings in the docker-compose.env file?
- What command did you execute that results in this error?
- Does docker exit immediately or do you have to exit that with CTRL+C?

**Comment by bwoodworth** [comment]
docker-compose.yml

```
version: "3.4"
services:
  broker:
    image: redis:6.0
    restart: always

  db:
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: jonaswinkler/paperless-ng:0.9.4
    restart: always
    depends_on:
      - db
      - broker
    ports:
      - 8880:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/paperless/data:/usr/src/paperless/data
      - /mnt/paperless/media:/usr/src/paperless/media
      - /mnt/paperless/export:/usr/src/paperless/export
      - /mnt/paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  pgdata:
```

docker-compose.env

```
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
USERMAP_UID=1000
USERMAP_GID=1000

# Additional languages to install for text recognition, separated by a
# whitespace. Note that this is
# different from PAPERLESS_OCR_LANGUAGE (default=eng), which defines the
# default language used when guessing the language from the OCR output.
# The container installs English, German, Italian, Spanish and French by
# default.
# See https://packages.debian.org/search?keywords=tesseract-ocr-&searchon=names&suite=buster
# for available languages.
#PAPERLESS_OCR_LANGUAGES=tur ces

###############################################################################
# Paperless-specific settings                                                 #
###############################################################################

# All settings defined in the paperless.conf.example can be used here. The
# Docker setup does not use the configuration file.
# A few commonly adjusted settings are provided below.

# Adjust this key if you plan to make paperless available publicly. It should
# be a very long sequence of random characters. You don't need to remember it.
#PAPERLESS_SECRET_KEY=change-me

# Use this variable to set a timezone for the Paperless Docker containers. If not specified, defaults to UTC.
PAPERLESS_TIME_ZONE=America/Los_Angeles

# The default language to use for OCR. Set this to the language most of your
# documents are written in.
PAPERLESS_OCR_LANGUAGE=eng

# By default Paperless does not OCR a document if the text can be retrieved from
# the document directly. Set to true to always OCR documents. (i.e., if you
# know that some of your documents have faulty/bad OCR data)
#PAPERLESS_OCR_ALWAYS=true

```

The error occurs when running docker-compose up -d to create the containers.  I am seeing the error when I view the logs in portainer.

The docker-compose up -d command completes successfully and it appears that the containers are running.
